# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Moving' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Moving
pod 'SwiftLint'
pod 'YouTubePlayer-Swift', '~> 1.0'
pod 'IQKeyboardManagerSwift'
pod 'lottie-ios'
pod 'Fabric'
pod 'Crashlytics'
pod 'GoogleAnalytics'
pod 'Firebase/Core'
pod 'RealmSwift'
end
